# Generated by Django 5.0.2 on 2026-03-30 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Завтрак"),
                            ("lunch", "Обед"),
                            ("dinner", "Ужин"),
                            ("snack", "Перекус"),
                        ],
                        max_length=20,
                        verbose_name="Тип приёма пищи",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="Дата")),
                (
                    "total_calories",
                    models.PositiveIntegerField(default=0, verbose_name="Калории"),
                ),
                (
                    "total_proteins",
                    models.PositiveIntegerField(default=0, verbose_name="Белки (г)"),
                ),
                (
                    "total_fats",
                    models.PositiveIntegerField(default=0, verbose_name="Жиры (г)"),
                ),
                (
                    "total_carbs",
                    models.PositiveIntegerField(default=0, verbose_name="Углеводы (г)"),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Продукт")),
                ("calories", models.PositiveIntegerField(verbose_name="Калории")),
                ("proteins", models.PositiveIntegerField(verbose_name="Белки")),
                ("fats", models.PositiveIntegerField(verbose_name="Жиры")),
                ("carbs", models.PositiveIntegerField(verbose_name="Углеводы")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=6,
                        verbose_name="Количество",
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_items",
                        to="nutrition.meal",
                    ),
                ),
            ],
        ),
    ]
