# Generated by Django 5.0.2 on 2026-03-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fooditem",
            options={"verbose_name": "Продукт", "verbose_name_plural": "Продукты"},
        ),
        migrations.AlterModelOptions(
            name="meal",
            options={
                "ordering": ["-date"],
                "verbose_name": "Приём пищи",
                "verbose_name_plural": "Приёмы пищи",
            },
        ),
        migrations.AlterField(
            model_name="meal",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Заметки"),
        ),
    ]
