# Generated by Django 5.1.7 on 2026-04-18 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0002_alter_fooditem_options_alter_meal_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="calories",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Калории",
            ),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="carbs",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Углеводы",
            ),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="fats",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Жиры",
            ),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="proteins",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Белки",
            ),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="Количество",
            ),
        ),
    ]
