# Generated by Django 5.1.7 on 2026-07-10 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hobbies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HobbyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="Дата")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Длительность (мин)"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Заметки")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hobby",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="hobbies.hobby",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог хобби",
                "verbose_name_plural": "Логи хобби",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
